name: binsight_ai
description: A Soundbendor Lab project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  path: ^1.8.3
  sqflite: ^2.3.0
  wifi_scan: ^0.4.0+2
  wifi_iot: ^0.3.18+1
  go_router: ^13.0.1
  web_socket_channel: ^2.4.0
  flutter_blue_plus: ^1.31.13
  provider: ^6.1.1
  sqflite_common_ffi: ^2.3.2
  flutter_spinkit: ^5.2.0
  syncfusion_flutter_charts: ^24.2.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.9
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_logo.png
  branding: assets/images/soundbendor_logo.png
  web: false

  android_12:
    color: "#ffffff"
    image: assets/images/app_logo.png
    branding: assets/images/soundbendor_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21
