name: binsight_ai
description: A Soundbendor Lab project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  path: ^1.0.0
  sqflite: ^2.0.0
  go_router: ^13.0.0
  web_socket_channel: ^2.0.0
  flutter_blue_plus: ^1.0.0
  provider: ^6.0.0
  sqflite_common_ffi: ^2.0.0
  flutter_spinkit: ^5.0.0
  flutter_reactive_ble: ^5.0.0
  permission_handler: ^11.0.0
  events_emitter: ^0.5.0
  introduction_screen: ^3.1.12
  dots_indicator: ^2.1.1
  syncfusion_flutter_charts: ^24.2.4+3
  intl: ^0.19.0
  url_launcher: ^6.2.4
  multiple_search_selection: ^2.6.3
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.7.0
  rotating_icon_button: ^1.0.0
  package_info_plus: ^8.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.0.0
  flutter_launcher_icons: ^0.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/

  fonts:
  - family: Georama
    fonts:
      - asset: assets/fonts/Georama-Bold.ttf
  - family: GolosText
    fonts:
      - asset: assets/fonts/GolosText-Regular.ttf
      - asset: assets/fonts/GolosText-SemiBold.ttf

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_logo.png
  branding: assets/images/soundbendor_logo.png
  web: false

  android_12:
    color: "#ffffff"
    image: assets/images/app_logo.png
    branding: assets/images/soundbendor_logo.png

flutter_launcher_icons:
  image_path: "assets/images/app_logo.png"
  android: true
  ios: true
  min_sdk_android: 21
