---
name: User Story Issue
about: Create a Issue with detailed user story information
title: "Section | Descriptive Title"
---

## Description
<!--- Describe your user story in detail -->
As a <type of user>, I want <some goal> so that <some reason>.

## Background

### Why?
<!--- Describe why this user story is important -->

### Who?
<!--- Describe who this user story is for -->

## Solution/Requirements
<!--- Describe the solution or requirements for this user story -->
* [ ] Complete example item 1

## Dependencies
<!--- Describe any dependencies for this user story -->
* [ ] Complete example item 1

## Definition of Done
<!--- Describe what it means for this user story to be done -->
* [ ] Complete example item 1
