name: build application
on:
  push:
    branches:
      - main
    tags:
      - release-*
  workflow_dispatch:

jobs:
  build-android:
    name: build android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v2
        with:
          name: app-release-android
          path: build/app/outputs/apk/release/
  build-ios:
    name: build ios
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64
      - run: flutter pub get
      - run: flutter test
      - run: flutter build ipa --release --no-codesign --export-method ad-hoc
      - uses: actions/upload-artifact@v3
        with:
          name: app-release-ios
          path: build/ios/ipa/
